site_name: ML Notes
site_url: https://tsljgj.github.io/ML-note
repo_url: https://github.com/tsljgj/ML-note
repo_name: tsljgj/ML-note
edit_uri: edit/main/docs/

# Contents
nav: 
  - About: index.md
  - Deep Learning:
    - Linear Models: dl/lnn.md
    - Softmax: dl/softmax.md
  - Dynamic Programming:
    - Basics: dp/basics.md
    - Linear DP: dp/linear.md
    - Knapsack: dp/knapsack.md
    - Interval DP: dp/interval.md
    - Tree DP: dp/tree.md

plugins:
  - glightbox
  - search

theme:
  font: 
    text: Times New Roman
  name: material
  # custom_dir: overrides 
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.instant.prefetch
    - navigation.instant.progress
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    logo: fontawesome/solid/dice-d20
    repo: fontawesome/brands/git-alt
    annotation: material/plus-circle-outline
    admonition:
      df: fontawesome/solid/pen-to-square
      nt: fontawesome/solid/circle-info
      rm: fontawesome/solid/thumbtack
      eg: fontawesome/solid/lightbulb
      ex: fontawesome/solid/rocket
      tm: fontawesome/solid/cube
      sl: fontawesome/solid/check
      im: fontawesome/solid/star
      pf: fontawesome/solid/key
      st: fontawesome/solid/chess-knight
      wr: fontawesome/solid/triangle-exclamation
      mt: fontawesome/solid/worm
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: custom

extra:
  generator: false
  social:
    - icon: fontawesome/solid/house
      link: https://tsljgj.github.io
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tsljgj
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/zhihaoy
    - icon: fontawesome/solid/paper-plane
      link: mailto:<zhihaoyu@andrew.cmu.edu>

extra_javascript:
  - javascripts/shortcuts.js
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/katex.js
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - stylesheets/extra.css
  - stylesheets/admonitions.css
  # - https://unpkg.com/katex@0/dist/katex.min.css

# Extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2024 Tsljgj
